Table "categories" {
  "category_id" smallint [not null]
  "category_name" "character varying(15)" [not null]
  "description" text
  "picture" bytea
}

Table "customer_customer_demo" {
  "customer_id" "character varying(5)" [not null]
  "customer_type_id" "character varying(5)" [not null]
}

Table "customer_demographics" {
  "customer_type_id" "character varying(5)" [not null]
  "customer_desc" text
}

Table "customers" {
  "customer_id" "character varying(5)" [not null]
  "company_name" "character varying(40)" [not null]
  "contact_name" "character varying(30)"
  "contact_title" "character varying(30)"
  "address" "character varying(60)"
  "city" "character varying(15)"
  "region" "character varying(15)"
  "postal_code" "character varying(10)"
  "country" "character varying(15)"
  "phone" "character varying(24)"
  "fax" "character varying(24)"
}

Table "employee_territories" {
  "employee_id" smallint [not null]
  "territory_id" "character varying(20)" [not null]
}

Table "employees" {
  "employee_id" smallint [not null]
  "last_name" "character varying(20)" [not null]
  "first_name" "character varying(10)" [not null]
  "title" "character varying(30)"
  "title_of_courtesy" "character varying(25)"
  "birth_date" date
  "hire_date" date
  "address" "character varying(60)"
  "city" "character varying(15)"
  "region" "character varying(15)"
  "postal_code" "character varying(10)"
  "country" "character varying(15)"
  "home_phone" "character varying(24)"
  "extension" "character varying(4)"
  "photo" bytea
  "notes" text
  "reports_to" smallint
  "photo_path" "character varying(255)"
}

Table "order_details" {
  "order_id" smallint [not null]
  "product_id" smallint [not null]
  "unit_price" real [not null]
  "quantity" smallint [not null]
  "discount" real [not null]
}

Table "orders" {
  "order_id" smallint [not null]
  "customer_id" "character varying(5)"
  "employee_id" smallint
  "order_date" date
  "required_date" date
  "shipped_date" date
  "ship_via" smallint
  "freight" real
  "ship_name" "character varying(40)"
  "ship_address" "character varying(60)"
  "ship_city" "character varying(15)"
  "ship_region" "character varying(15)"
  "ship_postal_code" "character varying(10)"
  "ship_country" "character varying(15)"
}

Table "products" {
  "product_id" smallint [not null]
  "product_name" "character varying(40)" [not null]
  "supplier_id" smallint
  "category_id" smallint
  "quantity_per_unit" "character varying(20)"
  "unit_price" real
  "units_in_stock" smallint
  "units_on_order" smallint
  "reorder_level" smallint
  "discontinued" integer [not null]
}

Table "region" {
  "region_id" smallint [not null]
  "region_description" "character varying(60)" [not null]
}

Table "shippers" {
  "shipper_id" smallint [not null]
  "company_name" "character varying(40)" [not null]
  "phone" "character varying(24)"
}

Table "suppliers" {
  "supplier_id" smallint [not null]
  "company_name" "character varying(40)" [not null]
  "contact_name" "character varying(30)"
  "contact_title" "character varying(30)"
  "address" "character varying(60)"
  "city" "character varying(15)"
  "region" "character varying(15)"
  "postal_code" "character varying(10)"
  "country" "character varying(15)"
  "phone" "character varying(24)"
  "fax" "character varying(24)"
  "homepage" text
}

Table "territories" {
  "territory_id" "character varying(20)" [not null]
  "territory_description" "character varying(60)" [not null]
  "region_id" smallint [not null]
}

Table "us_states" {
  "state_id" smallint [not null]
  "state_name" "character varying(100)"
  "state_abbr" "character varying(2)"
  "state_region" "character varying(50)"
}

Ref "fk_customer_customer_demo_customer_demographics":"customer_demographics"."customer_type_id" < "customer_customer_demo"."customer_type_id"

Ref "fk_customer_customer_demo_customers":"customers"."customer_id" < "customer_customer_demo"."customer_id"

Ref "fk_employee_territories_employees":"employees"."employee_id" < "employee_territories"."employee_id"

Ref "fk_employee_territories_territories":"territories"."territory_id" < "employee_territories"."territory_id"

Ref "fk_employees_employees":"employees"."employee_id" < "employees"."reports_to"

Ref "fk_order_details_orders":"orders"."order_id" < "order_details"."order_id"

Ref "fk_order_details_products":"products"."product_id" < "order_details"."product_id"

Ref "fk_orders_customers":"customers"."customer_id" < "orders"."customer_id"

Ref "fk_orders_employees":"employees"."employee_id" < "orders"."employee_id"

Ref "fk_orders_shippers":"shippers"."shipper_id" < "orders"."ship_via"

Ref "fk_products_categories":"categories"."category_id" < "products"."category_id"

Ref "fk_products_suppliers":"suppliers"."supplier_id" < "products"."supplier_id"

Ref "fk_territories_region":"region"."region_id" < "territories"."region_id"

